INSERT INTO category (category_id, category_name) VALUES
(1, 'FOOD'),
(2, 'TRANSPORT'),
(3, 'ENTERTAINMENT'),
(4, 'GROCERIES'),
(5, 'UTILITIES'),
(6, 'HEALTHCARE'),
(7, 'EDUCATION'),
(8, 'SHOPPING'),
(9, 'SUBSCRIPTIONS'),
(10, 'RENT'),
(11, 'EMERGENCY'),
(12, 'TRAVEL'),
(13, 'GIFTS'),
(14, 'INVESTMENT'),
(15, 'LOAN_PAYMENT'),
(16, 'OTHER');
